package com.example.student.covidstats

import android.os.AsyncTask


class Populate(db: CountryEntityRoomDatabase) : AsyncTask<Void, Void, Void>() {
    private var mDao: CountryEntityDao = db.countryEntityDao()
    override fun doInBackground(vararg params: Void?): Void? {
        mDao.insertContinent(ContinentCountryEntity("Angola","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Angola","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Burkina Faso","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Burundi","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Benin","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Botswana","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Congo (Kinshasa))","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Central African Republic","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Congo (Brazzaville))","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Côte d\"Ivoire","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Cameroon","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Cape Verde","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Djibouti","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Algeria","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Egypt","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Western Sahara","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Eritrea","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Ethiopia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Gabon","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Ghana","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Gambia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Guinea","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Equatorial Guinea","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Guinea-Bissau","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Kenya","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Comoros","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Liberia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Lesotho","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Libya","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Morocco","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Madagascar","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Mali","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Mauritania","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Mauritius","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Malawi","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Mozambique","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Namibia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Niger","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Nigeria","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Reunion","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Rwanda","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Seychelles","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Sudan","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Saint Helena","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Sierra Leone","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Senegal","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Somalia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Sao Tome and Principe","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Swaziland","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Chad","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Togo","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Tunisia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Tanzania","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Uganda","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Mayotte","Africa"))
        mDao.insertContinent(ContinentCountryEntity("South Africa","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Zambia","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Zimbabwe","Africa"))
        mDao.insertContinent(ContinentCountryEntity("Antarctica","Antarctica"))
        mDao.insertContinent(ContinentCountryEntity("Bouvet Island","Antarctica"))
        mDao.insertContinent(ContinentCountryEntity("South Georgia and South Sandwich Islands","Antarctica"))
        mDao.insertContinent(ContinentCountryEntity("Heard and McDonald Islands","Antarctica"))
        mDao.insertContinent(ContinentCountryEntity("French Southern Lands","Antarctica"))
        mDao.insertContinent(ContinentCountryEntity("United Arab Emirates","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Afghanistan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Armenia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Azerbaijan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Bangladesh","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Bahrain","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Brunei Darussalam","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Bhutan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Cocos (Keeling)) Islands","Asia"))
        mDao.insertContinent(ContinentCountryEntity("China","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Christmas Island","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Cyprus","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Georgia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Hong Kong","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Indonesia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Israel","Asia"))
        mDao.insertContinent(ContinentCountryEntity("India","Asia"))
        mDao.insertContinent(ContinentCountryEntity("British Indian Ocean Territory","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Iraq","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Iran","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Jordan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Japan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Kyrgyzstan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Cambodia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Korea, North","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Korea, South","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Kuwait","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Kazakhstan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Laos","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Lebanon","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Sri Lanka","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Myanmar","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Mongolia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Macau","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Maldives","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Malaysia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Nepal","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Oman","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Philippines","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Pakistan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Palestine","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Qatar","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Saudi Arabia","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Singapore","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Syria","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Thailand","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Tajikistan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Timor-Leste","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Turkmenistan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Turkey","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Taiwan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Uzbekistan","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Vietnam","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Yemen","Asia"))
        mDao.insertContinent(ContinentCountryEntity("Andorra","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Albania","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Austria","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Åland","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Bosnia and Herzegovina","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Belgium","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Bulgaria","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Belarus","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Switzerland","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Czech Republic","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Germany","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Denmark","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Estonia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Spain","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Finland","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Faroe Islands","Europe"))
        mDao.insertContinent(ContinentCountryEntity("France","Europe"))
        mDao.insertContinent(ContinentCountryEntity("United Kingdom","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Guernsey","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Gibraltar","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Greece","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Croatia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Hungary","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Ireland","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Isle of Man","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Iceland","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Italy","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Jersey","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Liechtenstein","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Lithuania","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Luxembourg","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Latvia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Monaco","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Moldova","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Montenegro","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Macedonia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Malta","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Netherlands","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Norway","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Poland","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Portugal","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Romania","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Serbia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Russian Federation","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Sweden","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Slovenia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Svalbard and Jan Mayen Islands","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Slovakia","Europe"))
        mDao.insertContinent(ContinentCountryEntity("San Marino","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Ukraine","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Vatican City","Europe"))
        mDao.insertContinent(ContinentCountryEntity("Antigua and Barbuda","North America"))
        mDao.insertContinent(ContinentCountryEntity("Anguilla","North America"))
        mDao.insertContinent(ContinentCountryEntity("Netherlands Antilles","North America"))
        mDao.insertContinent(ContinentCountryEntity("Aruba","North America"))
        mDao.insertContinent(ContinentCountryEntity("Barbados","North America"))
        mDao.insertContinent(ContinentCountryEntity("Saint Barthélemy","North America"))
        mDao.insertContinent(ContinentCountryEntity("Bermuda","North America"))
        mDao.insertContinent(ContinentCountryEntity("Bahamas","North America"))
        mDao.insertContinent(ContinentCountryEntity("Belize","North America"))
        mDao.insertContinent(ContinentCountryEntity("Canada","North America"))
        mDao.insertContinent(ContinentCountryEntity("Costa Rica","North America"))
        mDao.insertContinent(ContinentCountryEntity("Cuba","North America"))
        mDao.insertContinent(ContinentCountryEntity("Dominica","North America"))
        mDao.insertContinent(ContinentCountryEntity("Dominican Republic","North America"))
        mDao.insertContinent(ContinentCountryEntity("Grenada","North America"))
        mDao.insertContinent(ContinentCountryEntity("Greenland","North America"))
        mDao.insertContinent(ContinentCountryEntity("Guadeloupe","North America"))
        mDao.insertContinent(ContinentCountryEntity("Guatemala","North America"))
        mDao.insertContinent(ContinentCountryEntity("Honduras","North America"))
        mDao.insertContinent(ContinentCountryEntity("Haiti","North America"))
        mDao.insertContinent(ContinentCountryEntity("Jamaica","North America"))
        mDao.insertContinent(ContinentCountryEntity("Saint Kitts and Nevis","North America"))
        mDao.insertContinent(ContinentCountryEntity("Cayman Islands","North America"))
        mDao.insertContinent(ContinentCountryEntity("Saint Lucia","North America"))
        mDao.insertContinent(ContinentCountryEntity("Saint Martin (French part))","North America"))
        mDao.insertContinent(ContinentCountryEntity("Martinique","North America"))
        mDao.insertContinent(ContinentCountryEntity("Montserrat","North America"))
        mDao.insertContinent(ContinentCountryEntity("Mexico","North America"))
        mDao.insertContinent(ContinentCountryEntity("Nicaragua","North America"))
        mDao.insertContinent(ContinentCountryEntity("Panama","North America"))
        mDao.insertContinent(ContinentCountryEntity("Saint Pierre and Miquelon","North America"))
        mDao.insertContinent(ContinentCountryEntity("Puerto Rico","North America"))
        mDao.insertContinent(ContinentCountryEntity("El Salvador","North America"))
        mDao.insertContinent(ContinentCountryEntity("Turks and Caicos Islands","North America"))
        mDao.insertContinent(ContinentCountryEntity("Trinidad and Tobago","North America"))
        mDao.insertContinent(ContinentCountryEntity("United States of America","North America"))
        mDao.insertContinent(ContinentCountryEntity("Saint Vincent and the Grenadines","North America"))
        mDao.insertContinent(ContinentCountryEntity("Virgin Islands, British","North America"))
        mDao.insertContinent(ContinentCountryEntity("Virgin Islands, U.S.","North America"))
        mDao.insertContinent(ContinentCountryEntity("American Samoa","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Australia","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Cook Islands","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Fiji","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Micronesia","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Guam","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Kiribati","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Marshall Islands","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Northern Mariana Islands","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("New Caledonia","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Norfolk Island","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Nauru","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Niue","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("New Zealand","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("French Polynesia","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Papua New Guinea","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Pitcairn","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Palau","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Solomon Islands","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Tokelau","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Tonga","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Tuvalu","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("United States Minor Outlying Islands","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Vanuatu","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Wallis and Futuna Islands","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Samoa","Oceania"))
        mDao.insertContinent(ContinentCountryEntity("Argentina","South America"))
        mDao.insertContinent(ContinentCountryEntity("Bolivia","South America"))
        mDao.insertContinent(ContinentCountryEntity("Brazil","South America"))
        mDao.insertContinent(ContinentCountryEntity("Chile","South America"))
        mDao.insertContinent(ContinentCountryEntity("Colombia","South America"))
        mDao.insertContinent(ContinentCountryEntity("Ecuador","South America"))
        mDao.insertContinent(ContinentCountryEntity("Falkland Islands","South America"))
        mDao.insertContinent(ContinentCountryEntity("French Guiana","South America"))
        mDao.insertContinent(ContinentCountryEntity("Guyana","South America"))
        mDao.insertContinent(ContinentCountryEntity("Peru","South America"))
        mDao.insertContinent(ContinentCountryEntity("Paraguay","South America"))
        mDao.insertContinent(ContinentCountryEntity("Suriname","South America"))
        mDao.insertContinent(ContinentCountryEntity("Uruguay","South America"))
        mDao.insertContinent(ContinentCountryEntity("Venezuela","South America"))

        return null
    }

}